---
title: "Using Custom Databases in Sirius"
output:
    BiocStyle::html_document:
        toc_float: true
vignette: >
    %\VignetteIndexEntry{Using Custom Databases in Sirius}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
    %\VignettePackage{RuSirius}
    %\VignetteDepends{RSirius, RuSirius, MsDataHub, Spectra}
---

<!--
# Pre-render with (in the vignettes folder)
knitr::knit("CustomDatabases.Rmd.orig", output = "CustomDatabases.Rmd")
-->




``` r
library(RSirius)
library(RuSirius)
library(MsDataHub)
library(Spectra)
```

## Introduction

**Note**: this vignette is
[**pre-computed**](https://ropensci.org/blog/2019/12/08/precompute-vignettes/).
See the session info for information on packages used and the date the vignette
was rendered. The vignette requires a running
[Sirius](https://bio.informatik.uni-jena.de/software/sirius/) instance. To
reproduce this analysis, you will need Sirius 6.3 installed and running.

Sirius can search against custom databases in addition to the built-in
databases (BIO, PubChem, etc.). This is useful when you have:

- A list of suspect compounds specific to your study
- A custom spectral library (e.g., from MassBank)
- Target compounds you want to prioritize in the search

This vignette demonstrates how to create and use custom databases, and shows
the impact on structure identification results.

## Managing Databases

### Listing Available Databases


``` r
srs <- Sirius(port = 9999)
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.
#> Could not find sirius.port file. Please terminate SIRIUS if needed and try specifying a port
#> Alternatively, try attaching to a running SIRIUS instance with attach_to_running_sirius()
#> An Exception occurred while trying to gracefully shutdown SIRIUS!
#> attempt to apply non-function 
#> Sirius process has been terminated.
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.
#> Could not find sirius.port file. Please terminate SIRIUS if needed and try specifying a port
#> Alternatively, try attaching to a running SIRIUS instance with attach_to_running_sirius()
#> An Exception occurred while trying to gracefully shutdown SIRIUS!
#> attempt to apply non-function 
#> Sirius process has been terminated.
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.

# List all searchable databases
dbs <- listDbs(srs)
dbs[, c("databaseId", "displayName")]
#>                         databaseId
#> 1                              ALL
#> 2                              BIO
#> 3                          PUBCHEM
#> 4                             MESH
#> 5                             HMDB
#> 6                         KNAPSACK
#> 7                            CHEBI
#> 8                           PUBMED
#> 9                             KEGG
#> 10                            HSDB
#> 11                         MACONDA
#> 12                         METACYC
#> 13                            GNPS
#> 14                           TRAIN
#> 15                            YMDB
#> 16                        PLANTCYC
#> 17                          NORMAN
#> 18                    SUPERNATURAL
#> 19                         COCONUT
#> 20                   BloodExposome
#> 21                         TeroMol
#> 22            PUBCHEMANNOTATIONBIO
#> 23           PUBCHEMANNOTATIONDRUG
#> 24 PUBCHEMANNOTATIONSAFETYANDTOXIC
#> 25           PUBCHEMANNOTATIONFOOD
#> 26                           LOTUS
#> 27                           FooDB
#> 28                          MiMeDB
#> 29                       LIPIDMAPS
#> 30                           LIPID
#> 31                          DSSTox
#>                     displayName
#> 1              All included DBs
#> 2                  Bio Database
#> 3                       PubChem
#> 4                          MeSH
#> 5                          HMDB
#> 6                      KNApSAcK
#> 7                         CHEBI
#> 8                        PubMed
#> 9                          KEGG
#> 10                         HSDB
#> 11                      Maconda
#> 12                       Biocyc
#> 13                         GNPS
#> 14                 Training Set
#> 15                         YMDB
#> 16                     Plantcyc
#> 17                       NORMAN
#> 18                 SuperNatural
#> 19                      COCONUT
#> 20               Blood Exposome
#> 21                      TeroMOL
#> 22 PubChem: bio and metabolites
#> 23                PubChem: drug
#> 24    PubChem: safety and toxic
#> 25                PubChem: food
#> 26                        LOTUS
#> 27                        FooDB
#> 28                       MiMeDB
#> 29                    LipidMaps
#> 30                        Lipid
#> 31                       DSSTox
```

### Database Information


``` r
# Get details about a specific database
infoDb(srs, databaseId = "BIO")
#> $displayName
#> [1] "Bio Database"
#> 
#> $matchRtOfReferenceSpectra
#> [1] FALSE
#> 
#> $databaseId
#> [1] "BIO"
#> 
#> $customDb
#> [1] FALSE
#> 
#> $searchable
#> [1] TRUE
#> 
#> $updateNeeded
#> [1] FALSE
```

## Creating a Custom Database

Custom databases can be created from files containing compound information.
Supported formats include `.tsv`, `.csv`, or `.mgf` files with structure
information.

### From a Compound List (TSV/CSV)

The file should contain columns for compound name, SMILES (or InChI), and
optionally the molecular formula.


``` r
# Create database from a TSV file
createDb(srs,
         databaseId = "my_suspects",
         files = "path/to/suspects.tsv",
         location = getwd())

# Verify it was created
listDbs(srs)
```

### From a Spectral Library (MGF)

Spectral libraries in MGF format can also be imported. An example MGF file is
included in the package:


``` r
# Path to example MassBank MGF file
mgf_file <- system.file("vignettes", "MASSBANKEU.mgf", package = "RuSirius")

createDb(srs,
         databaseId = "massbank_custom",
         files = mgf_file,
         location = getwd())
#> $displayName
#> [1] "massbank_custom"
#> 
#> $location
#> [1] "C:\\Users\\phili\\.sirius-6.3\\csi_fingerid_cache\\custom.siriusdb"
#> 
#> $matchRtOfReferenceSpectra
#> [1] FALSE
#> 
#> $databaseId
#> [1] "massbank_custom"
#> 
#> $customDb
#> [1] TRUE
#> 
#> $searchable
#> [1] TRUE
#> 
#> $dbVersion
#> [1] 3
#> 
#> $updateNeeded
#> [1] FALSE
#> 
#> $numberOfStructures
#> [1] 652
#> 
#> $numberOfFormulas
#> [1] 581
#> 
#> $numberOfReferenceSpectra
#> [1] 1304
```

## Comparing Results: Default vs Custom Database

Let's demonstrate how using a custom database affects structure identification.

### Setup: Import Sample Data


``` r
# Load example data
dda_file <- MsDataHub::PestMix1_DDA.mzML()
sp <- Spectra(dda_file)
sp <- setBackend(sp, MsBackendMemory())
sp <- filterEmptySpectra(sp)

# Group spectra
idxs <- fragmentGroupIndex(sp)
sp$Msn_idx <- idxs

# Create project and import
srs <- Sirius(projectId = "db_comparison", path = getwd(), port = 9999)
sp_subset <- sp[sp$Msn_idx %in% c(421, 707)]
srs <- import(srs, spectra = sp_subset, ms_column_name = "Msn_idx")
```

### Run with Default Database (BIO)


``` r
# Run structure search with BIO database only
run(srs,
    formulaIdParams = formulaIdParam(numberOfCandidates = 5),
    predictParams = predictParam(),
    structureDbSearchParams = structureDbSearchParam(
        structureSearchDbs = c("BIO")
    ),
    recompute = TRUE,
    wait = TRUE)
#> [1] "1"

# Get results
results_bio <- summary(srs, result.type = "structure")
results_bio[, c("alignedFeatureId", "molecularFormula",
                "structureName", "confidenceExactMatch")]
#>     alignedFeatureId molecularFormula
#> 1 822428714056778629        C9H16N2O4
#> 2 822428714195190662     C15H20F6N2O5
#>                                                                                                                  structureName
#> 1                                                                         Malonic acid, oxo-, diethyl ester, dimethylhydrazone
#> 2 tert-butyl-(3R)-3-{[5-(2,2,2-trifluoro-1-hydroxy-1-trifluoromethyl-ethyl)-4,5-dihydro-isoxazole-3-carbonyl]-amino}-butanoate
#>   confidenceExactMatch
#> 1           0.07049930
#> 2           0.04112307
```

### Run with Custom Database Added


``` r
# Now include custom database in search
run(srs,
    formulaIdParams = formulaIdParam(numberOfCandidates = 5),
    predictParams = predictParam(),
    structureDbSearchParams = structureDbSearchParam(
        structureSearchDbs = c("BIO", "massbank_custom")
    ),
    recompute = TRUE,
    wait = TRUE)
#> [1] "2"

# Get results with custom DB
results_custom <- summary(srs, result.type = "structure")
results_custom[, c("alignedFeatureId", "molecularFormula",
                   "structureName", "confidenceExactMatch")]
#>     alignedFeatureId molecularFormula
#> 1 822428714056778629        C9H16N2O4
#> 2 822428714195190662     C15H20F6N2O5
#>                                                                                                                  structureName
#> 1                                                                         Malonic acid, oxo-, diethyl ester, dimethylhydrazone
#> 2 tert-butyl-(3R)-3-{[5-(2,2,2-trifluoro-1-hydroxy-1-trifluoromethyl-ethyl)-4,5-dihydro-isoxazole-3-carbonyl]-amino}-butanoate
#>   confidenceExactMatch
#> 1           0.07049930
#> 2           0.04112307
```

### Compare Results


``` r
# Compare confidence scores
comparison <- merge(
    results_bio[, c("alignedFeatureId", "confidenceExactMatch")],
    results_custom[, c("alignedFeatureId", "confidenceExactMatch")],
    by = "alignedFeatureId",
    suffixes = c("_bio", "_custom")
)
comparison
#>     alignedFeatureId
#> 1 822428714056778629
#> 2 822428714195190662
#>   confidenceExactMatch_bio
#> 1               0.07049930
#> 2               0.04112307
#>   confidenceExactMatch_custom
#> 1                  0.07049930
#> 2                  0.04112307
```

Including relevant custom databases can improve identification confidence when
your compounds are well-represented in the custom database.

## Removing a Database


``` r
# Remove a custom database when no longer needed
removeDb(srs, databaseId = "massbank_custom")
#> [1] TRUE

# Verify removal
listDbs(srs)
#>                     displayName
#> 1              All included DBs
#> 2                  Bio Database
#> 3                       PubChem
#> 4                          MeSH
#> 5                          HMDB
#> 6                      KNApSAcK
#> 7                         CHEBI
#> 8                        PubMed
#> 9                          KEGG
#> 10                         HSDB
#> 11                      Maconda
#> 12                       Biocyc
#> 13                         GNPS
#> 14                 Training Set
#> 15                         YMDB
#> 16                     Plantcyc
#> 17                       NORMAN
#> 18                 SuperNatural
#> 19                      COCONUT
#> 20               Blood Exposome
#> 21                      TeroMOL
#> 22 PubChem: bio and metabolites
#> 23                PubChem: drug
#> 24    PubChem: safety and toxic
#> 25                PubChem: food
#> 26                        LOTUS
#> 27                        FooDB
#> 28                       MiMeDB
#> 29                    LipidMaps
#> 30                        Lipid
#> 31                       DSSTox
#>    matchRtOfReferenceSpectra
#> 1                      FALSE
#> 2                      FALSE
#> 3                      FALSE
#> 4                      FALSE
#> 5                      FALSE
#> 6                      FALSE
#> 7                      FALSE
#> 8                      FALSE
#> 9                      FALSE
#> 10                     FALSE
#> 11                     FALSE
#> 12                     FALSE
#> 13                     FALSE
#> 14                     FALSE
#> 15                     FALSE
#> 16                     FALSE
#> 17                     FALSE
#> 18                     FALSE
#> 19                     FALSE
#> 20                     FALSE
#> 21                     FALSE
#> 22                     FALSE
#> 23                     FALSE
#> 24                     FALSE
#> 25                     FALSE
#> 26                     FALSE
#> 27                     FALSE
#> 28                     FALSE
#> 29                     FALSE
#> 30                     FALSE
#> 31                     FALSE
#>                         databaseId
#> 1                              ALL
#> 2                              BIO
#> 3                          PUBCHEM
#> 4                             MESH
#> 5                             HMDB
#> 6                         KNAPSACK
#> 7                            CHEBI
#> 8                           PUBMED
#> 9                             KEGG
#> 10                            HSDB
#> 11                         MACONDA
#> 12                         METACYC
#> 13                            GNPS
#> 14                           TRAIN
#> 15                            YMDB
#> 16                        PLANTCYC
#> 17                          NORMAN
#> 18                    SUPERNATURAL
#> 19                         COCONUT
#> 20                   BloodExposome
#> 21                         TeroMol
#> 22            PUBCHEMANNOTATIONBIO
#> 23           PUBCHEMANNOTATIONDRUG
#> 24 PUBCHEMANNOTATIONSAFETYANDTOXIC
#> 25           PUBCHEMANNOTATIONFOOD
#> 26                           LOTUS
#> 27                           FooDB
#> 28                          MiMeDB
#> 29                       LIPIDMAPS
#> 30                           LIPID
#> 31                          DSSTox
#>    customDb searchable updateNeeded
#> 1     FALSE      FALSE        FALSE
#> 2     FALSE       TRUE        FALSE
#> 3     FALSE       TRUE        FALSE
#> 4     FALSE       TRUE        FALSE
#> 5     FALSE       TRUE        FALSE
#> 6     FALSE       TRUE        FALSE
#> 7     FALSE       TRUE        FALSE
#> 8     FALSE       TRUE        FALSE
#> 9     FALSE       TRUE        FALSE
#> 10    FALSE       TRUE        FALSE
#> 11    FALSE       TRUE        FALSE
#> 12    FALSE       TRUE        FALSE
#> 13    FALSE       TRUE        FALSE
#> 14    FALSE      FALSE        FALSE
#> 15    FALSE       TRUE        FALSE
#> 16    FALSE       TRUE        FALSE
#> 17    FALSE       TRUE        FALSE
#> 18    FALSE       TRUE        FALSE
#> 19    FALSE       TRUE        FALSE
#> 20    FALSE       TRUE        FALSE
#> 21    FALSE       TRUE        FALSE
#> 22    FALSE       TRUE        FALSE
#> 23    FALSE       TRUE        FALSE
#> 24    FALSE       TRUE        FALSE
#> 25    FALSE       TRUE        FALSE
#> 26    FALSE       TRUE        FALSE
#> 27    FALSE       TRUE        FALSE
#> 28    FALSE       TRUE        FALSE
#> 29    FALSE       TRUE        FALSE
#> 30    FALSE      FALSE        FALSE
#> 31    FALSE       TRUE        FALSE
```

## Best Practices

1. **Targeted databases**: Create focused databases with compounds relevant to
   your study rather than very large generic databases.

2. **Quality over quantity**: Ensure your custom database has accurate
   structure information (SMILES/InChI).

3. **Combine strategically**: Use custom databases alongside BIO for best
   coverage - BIO for general metabolites, custom for your specific targets.

4. **Spectral libraries**: When available, spectral libraries (MGF) provide
   additional matching power through spectral similarity.

## Clean Up


``` r
shutdown(srs)
#> Sirius was shut down successfully
```

# Session information

The R code was run on:


``` r
date()
#> [1] "Thu Mar 19 12:18:56 2026"
```

Information on the R session:


``` r
sessionInfo()
#> R version 4.5.2 (2025-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 11 x64 (build 26200)
#> 
#> Matrix products: default
#>   LAPACK version 3.12.1
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.utf8 
#> [2] LC_CTYPE=English_United Kingdom.utf8   
#> [3] LC_MONETARY=English_United Kingdom.utf8
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.utf8    
#> 
#> time zone: Europe/Paris
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats4    stats     graphics 
#> [4] grDevices utils     datasets 
#> [7] methods   base     
#> 
#> other attached packages:
#>  [1] RuSirius_1.0.0         
#>  [2] MsDataHub_1.10.0       
#>  [3] dplyr_1.2.0            
#>  [4] MetaboAnnotation_1.14.0
#>  [5] xcms_4.8.0             
#>  [6] MsExperiment_1.12.0    
#>  [7] BiocStyle_2.38.0       
#>  [8] testthat_3.3.2         
#>  [9] Spectra_1.20.1         
#> [10] BiocParallel_1.44.0    
#> [11] S4Vectors_0.48.0       
#> [12] BiocGenerics_0.56.0    
#> [13] generics_0.1.4         
#> [14] RSirius_6.3.3          
#> [15] ProtGenerics_1.42.0    
#> 
#> loaded via a namespace (and not attached):
#>   [1] bitops_1.0-9               
#>   [2] filelock_1.0.3             
#>   [3] tibble_3.3.1               
#>   [4] preprocessCore_1.72.0      
#>   [5] XML_3.99-0.22              
#>   [6] lifecycle_1.0.5            
#>   [7] httr2_1.2.2                
#>   [8] doParallel_1.0.17          
#>   [9] rprojroot_2.1.1            
#>  [10] processx_3.8.6             
#>  [11] lattice_0.22-7             
#>  [12] MASS_7.3-65                
#>  [13] MultiAssayExperiment_1.36.1
#>  [14] magrittr_2.0.4             
#>  [15] limma_3.66.0               
#>  [16] sass_0.4.10                
#>  [17] rmarkdown_2.30             
#>  [18] jquerylib_0.1.4            
#>  [19] yaml_2.3.12                
#>  [20] remotes_2.5.0              
#>  [21] otel_0.2.0                 
#>  [22] sessioninfo_1.2.3          
#>  [23] pkgbuild_1.4.8             
#>  [24] MsCoreUtils_1.22.1         
#>  [25] DBI_1.2.3                  
#>  [26] RColorBrewer_1.1-3         
#>  [27] abind_1.4-8                
#>  [28] pkgload_1.5.0              
#>  [29] GenomicRanges_1.62.1       
#>  [30] purrr_1.2.1                
#>  [31] AnnotationFilter_1.34.0    
#>  [32] RCurl_1.98-1.17            
#>  [33] rappdirs_0.3.4             
#>  [34] IRanges_2.44.0             
#>  [35] MSnbase_2.36.0             
#>  [36] commonmark_2.0.0           
#>  [37] ncdf4_1.24                 
#>  [38] codetools_0.2-20           
#>  [39] CompoundDb_1.14.2          
#>  [40] DelayedArray_0.36.0        
#>  [41] DT_0.34.0                  
#>  [42] xml2_1.5.2                 
#>  [43] tidyselect_1.2.1           
#>  [44] farver_2.1.2               
#>  [45] matrixStats_1.5.0          
#>  [46] BiocFileCache_3.0.0        
#>  [47] base64enc_0.1-6            
#>  [48] Seqinfo_1.0.0              
#>  [49] roxygen2_7.3.3             
#>  [50] diffobj_0.3.6              
#>  [51] jsonlite_2.0.0             
#>  [52] ellipsis_0.3.2             
#>  [53] iterators_1.0.14           
#>  [54] foreach_1.5.2              
#>  [55] progress_1.2.3             
#>  [56] tools_4.5.2                
#>  [57] snow_0.4-4                 
#>  [58] Rcpp_1.1.1                 
#>  [59] glue_1.8.0                 
#>  [60] gridExtra_2.3              
#>  [61] SparseArray_1.10.8         
#>  [62] BiocBaseUtils_1.12.0       
#>  [63] xfun_0.56                  
#>  [64] MatrixGenerics_1.22.0      
#>  [65] usethis_3.2.1              
#>  [66] withr_3.0.2                
#>  [67] BiocManager_1.30.27        
#>  [68] fastmap_1.2.0              
#>  [69] xopen_1.0.1                
#>  [70] callr_3.7.6                
#>  [71] digest_0.6.39              
#>  [72] rcmdcheck_1.4.0            
#>  [73] R6_2.6.1                   
#>  [74] rsvg_2.7.0                 
#>  [75] RSQLite_2.4.6              
#>  [76] tidyr_1.3.2                
#>  [77] data.table_1.18.2.1        
#>  [78] prettyunits_1.2.0          
#>  [79] PSMatch_1.14.0             
#>  [80] httr_1.4.8                 
#>  [81] htmlwidgets_1.6.4          
#>  [82] S4Arrays_1.10.1            
#>  [83] pkgconfig_2.0.3            
#>  [84] gtable_0.3.6               
#>  [85] blob_1.3.0                 
#>  [86] S7_0.2.1                   
#>  [87] impute_1.84.0              
#>  [88] MassSpecWavelet_1.76.0     
#>  [89] XVector_0.50.0             
#>  [90] brio_1.1.5                 
#>  [91] htmltools_0.5.9            
#>  [92] bookdown_0.46              
#>  [93] MALDIquant_1.22.3          
#>  [94] clue_0.3-67                
#>  [95] scales_1.4.0               
#>  [96] Biobase_2.70.0             
#>  [97] png_0.1-8                  
#>  [98] knitr_1.51                 
#>  [99] MetaboCoreUtils_1.19.2     
#> [100] rstudioapi_0.18.0          
#> [101] reshape2_1.4.5             
#> [102] rjson_0.2.23               
#> [103] curl_7.0.0                 
#> [104] cachem_1.1.0               
#> [105] stringr_1.6.0              
#> [106] BiocVersion_3.22.0         
#> [107] parallel_4.5.2             
#> [108] mzID_1.48.0                
#> [109] AnnotationDbi_1.72.0       
#> [110] vsn_3.78.1                 
#> [111] desc_1.4.3                 
#> [112] pillar_1.11.1              
#> [113] grid_4.5.2                 
#> [114] vctrs_0.7.1                
#> [115] MsFeatures_1.18.0          
#> [116] pcaMethods_2.2.0           
#> [117] dbplyr_2.5.2               
#> [118] cluster_2.1.8.1            
#> [119] waldo_0.6.2                
#> [120] evaluate_1.0.5             
#> [121] cli_3.6.5                  
#> [122] compiler_4.5.2             
#> [123] rlang_1.1.7                
#> [124] crayon_1.5.3               
#> [125] QFeatures_1.20.0           
#> [126] ChemmineR_3.62.0           
#> [127] ps_1.9.1                   
#> [128] affy_1.88.0                
#> [129] plyr_1.8.9                 
#> [130] fs_1.6.6                   
#> [131] stringi_1.8.7              
#> [132] Biostrings_2.78.0          
#> [133] lazyeval_0.2.2             
#> [134] devtools_2.4.6             
#> [135] Matrix_1.7-4               
#> [136] ExperimentHub_3.0.0        
#> [137] hms_1.1.4                  
#> [138] bit64_4.6.0-1              
#> [139] ggplot2_4.0.2              
#> [140] KEGGREST_1.50.0            
#> [141] statmod_1.5.1              
#> [142] SummarizedExperiment_1.40.0
#> [143] AnnotationHub_4.0.0        
#> [144] mzR_2.44.0                 
#> [145] igraph_2.2.2               
#> [146] memoise_2.0.1              
#> [147] affyio_1.80.0              
#> [148] bslib_0.10.0               
#> [149] bit_4.6.0
```
