---
title: "Importing Spectra into Sirius"
output:
    BiocStyle::html_document:
        toc_float: true
vignette: >
    %\VignetteIndexEntry{Importing Spectra into Sirius}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
    %\VignettePackage{RuSirius}
    %\VignetteDepends{Spectra, RSirius, RuSirius, MsDataHub}
---

<!--
# Pre-render with (in the vignettes folder)
knitr::knit("ImportSpectra.Rmd.orig", output = "ImportSpectra.Rmd")
-->




``` r
library(RuSirius)
library(MsDataHub)
library(Spectra)
```

## Introduction

**Note**: this vignette is
[**pre-computed**](https://ropensci.org/blog/2019/12/08/precompute-vignettes/).
See the session info for information on packages used and the date the vignette
was rendered. The vignette requires a running
[Sirius](https://bio.informatik.uni-jena.de/software/sirius/) instance. To
reproduce this analysis, you will need Sirius 6.3 installed and running.

This vignette demonstrates a basic workflow for importing MS data in a Spectra
object object into *Sirius*. It then runs Sirius's main tools: formula
identification, structure database search, compound class prediction, spectral
library matching, *de novo* structure prediction, and finally retrieves the
results.

This is a foundational example and does not cover all the possible parameters
for each Sirius tool. For detailed parameter information, consult the `run()`
function documentation. More information can be found in the [Sirius
documentation online](https://v6.docs.sirius-ms.io/).

**IMPORTANT:** This is a work in progress. Feedback is highly valued, especially
regarding enhancements or additions that could simplify your workflow. Your
input as a user is essential.

## Prepping Spectra object

Below we load the example mass spectrometry (MS) data, provided by the
*MsDataHub*, as a `Spectra` object:


``` r
dda_file <- MsDataHub::PestMix1_DDA.mzML()
sp <- Spectra(dda_file)
sp <- setBackend(sp, MsBackendMemory())
sp <- filterEmptySpectra(sp)
```

To import the `Spectra` data into *Sirius*, it must be preprocessed. If spectra
from multiple MS levels are present, we need to group them appropriately.

We use the `fragmentGroupIndex()` function to assign an index to each spectrum.
MS2 spectra that belong to the same MS1 spectrum will share the same index. See
`?fragmentGroupIndex` for details on how these spectra groups are defined.


``` r
sp |>
    msLevel() |>
    table()
#> 
#>    1    2 
#> 4627 2756

idxs <- fragmentGroupIndex(sp)
sp$Msn_idx <- idxs
```

## Open Sirius and project set up

The Sirius application is initialized via the API, requiring only a project ID.
If the project exists, it is opened; otherwise, a new project is created. The
`srs` object acts as the connection to Sirius and holds project details.
Properly shut down the connection with `shutdown(srs)` after completing your
work.

This `srs` variable is needed for any task that necessitate to communicate with
the application. You can learn more about this object class by running `?Sirius`
in the console. Below I do not precise the `path` parameter, by default Sirius
will try save your project in the `sirius_projects` folder in your user
directory. Note that this folder will *not* be created automatically. If you
want to save it somewhere else you can specify the `path =` parameter.


``` r
srs <- Sirius(projectId = "test_spectra", path = getwd(), port = 9999)
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.
#> Could not find sirius.port file. Please terminate SIRIUS if needed and try specifying a port
#> Alternatively, try attaching to a running SIRIUS instance with attach_to_running_sirius()
#> An Exception occurred while trying to gracefully shutdown SIRIUS!
#> attempt to apply non-function 
#> Sirius process has been terminated.
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.
#> Could not find sirius.port file. Please terminate SIRIUS if needed and try specifying a port
#> Alternatively, try attaching to a running SIRIUS instance with attach_to_running_sirius()
#> An Exception occurred while trying to gracefully shutdown SIRIUS!
#> attempt to apply non-function 
#> Sirius process has been terminated.
#> Found SIRIUS in PATH! Using this information to start the application.
#> SIRIUS was started without specifying --port (-p), trying to find the sirius.port file.
```

You could import the entire `Spectra` object, but for demonstration purposes, we
will use selected examples.

Here, we import two MS1-MS2 pairs and one MS1 spectrum on its own. It's also
possible to import only MS2 spectra.

When importing, the `ms_column_name` parameter defines which column contains the
index that groups the spectra. Each such group is considered one *feature* in
Sirius terminology.


``` r
sp_subset <- sp[sp$Msn_idx %in% c(421, 707, 895)]

srs <- import(sirius = srs,
              spectra = sp_subset,
              ms_column_name = "Msn_idx",
              deleteExistingFeatures = TRUE)

## See information about the features
featuresInfo(srs)
#>      alignedFeatureId    
#> [1,] "822429489429436694"
#> [2,] "822429489530099991"
#> [3,] "822429489580431640"
#>      compoundId          
#> [1,] "822429489383299347"
#> [2,] "822429489383299348"
#> [3,] "822429489383299349"
#>      externalFeatureId ionMass 
#> [1,] "421"             217.1185
#> [2,] "707"             445.1181
#> [3,] "895"             0       
#>      charge detectedAdducts hasMs1
#> [1,] 1      list,1          TRUE  
#> [2,] 1      list,1          TRUE  
#> [3,] 1      list,1          TRUE  
#>      hasMsMs computing
#> [1,] TRUE    FALSE    
#> [2,] TRUE    FALSE    
#> [3,] FALSE   FALSE
```

## Submit job to Sirius - For structure DB search

Once data is imported, annotation and prediction can begin. The `run()` function
accepts parameters for each Sirius tool, such as formula identification,
structure database search, and compound class prediction.


``` r
## Start computation
run(srs,
    fallbackAdducts = c("[M + H]+", "[M + Na]+"),
    formulaIdParams = formulaIdParam(numberOfCandidates = 10,
                                       instrument = "QTOF",
                        numberOfCandidatesPerIonization = 3,
                        massAccuracyMS2ppm = 10,
                        filterByIsotopePattern = FALSE,
                        isotopeMs2Settings = c("SCORE"),
                        performDeNovoBelowMz = 600,
                        minPeaksToInjectSpecLibMatch = 3),
    predictParams = predictParam(),

    structureDbSearchParams = structureDbSearchParam(
          structureSearchDbs = c("BIO")
      ),
    recompute = TRUE,
    wait = TRUE
    )
#> [1] "1"

## could test featureInfo vs featureId
info <- featuresInfo(srs)
```

## Retrieve Results

To get a summary of all results—including top formulas, structures, and compound
class predictions—use the following:


``` r
summarytb <- summary(srs, result.type = "structure")
```

This summary table offers a quick overview for checking whether the predictions
meet expectations. However, we recommend not relying solely on it for in-depth
analysis. Instead, use the more detailed functions provided later in this
vignette.

Key columns include confidence scores that help assess result reliability.

## De novo structure description


``` r
# Compute with zodiac and denovo
run(srs,
    msNovelistParams = deNovoStructureParam(numberOfCandidateToPredict = 5),
    recompute = FALSE,
    wait = TRUE
)
#> [1] "2"

summaryDeNovo <- summary(srs, result.type = "deNovo")
```

Interestingly, for the first feature, the results remain consistent, while for
the second—originally having lower confidence—the predictions now differ.

For a visual exploration of results, you can open the Sirius GUI:


``` r
shutdown(srs)
#> Sirius was shut down successfully

# openGUI(srs)
# closeGUI(srs)
```

You can look more into retrieving the other results in the `?results`
documentation. or the other vignette.

## Importing MS2-only or MSn-only data

In some workflows, only MS2 (or MS2 and MS3) spectra are available — for
example, when working with spectral libraries, MGF files, or data that was
acquired without recording MS1 scans.

The SIRIUS API fully supports importing features without MS1 data. When no MS1
spectra are present and no `ms_column_name` is provided, `import()`
automatically groups MSn spectra by acquisition order: within each file
(`dataOrigin`), a new group starts whenever a new MS2 `precursorMz` is
encountered, and any subsequent higher-level scans (MS3+) are assigned to the
same group as their preceding MS2. With `deleteExistingFeatures = TRUE` any
eventually present previously imported spectra (*features*) and their results
are removed.


``` r
## Example: importing MS2-only spectra
## Assume sp_ms2 is a Spectra object containing only MS2 (and optionally MS3)
## spectra, with no MS1 data.
sp_ms2 <- filterMsLevel(sp, msLevel = 2L)
sp_ms2 <- sp_ms2[1:10]  # Just an example subset of MS2 spectra
## No need for ms_column_name — the function auto-groups by acquisition order.
srs <- import(sirius = srs,
              spectra = sp_ms2,
              deleteExistingFeatures = TRUE)

featuresInfo(srs)
```

If your MSn spectra already have a grouping column (e.g., from a feature
detection tool), you can still pass it via `ms_column_name` as usual.

# Session information

The R code was run on:


``` r
date()
#> [1] "Thu Mar 19 12:22:15 2026"
```

Information on the R session:


``` r
sessionInfo()
#> R version 4.5.2 (2025-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 11 x64 (build 26200)
#> 
#> Matrix products: default
#>   LAPACK version 3.12.1
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.utf8 
#> [2] LC_CTYPE=English_United Kingdom.utf8   
#> [3] LC_MONETARY=English_United Kingdom.utf8
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.utf8    
#> 
#> time zone: Europe/Paris
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats4    stats     graphics 
#> [4] grDevices utils     datasets 
#> [7] methods   base     
#> 
#> other attached packages:
#>  [1] RuSirius_1.0.0         
#>  [2] MsDataHub_1.10.0       
#>  [3] dplyr_1.2.0            
#>  [4] MetaboAnnotation_1.14.0
#>  [5] xcms_4.8.0             
#>  [6] MsExperiment_1.12.0    
#>  [7] BiocStyle_2.38.0       
#>  [8] testthat_3.3.2         
#>  [9] Spectra_1.20.1         
#> [10] BiocParallel_1.44.0    
#> [11] S4Vectors_0.48.0       
#> [12] BiocGenerics_0.56.0    
#> [13] generics_0.1.4         
#> [14] RSirius_6.3.3          
#> [15] ProtGenerics_1.42.0    
#> 
#> loaded via a namespace (and not attached):
#>   [1] bitops_1.0-9               
#>   [2] filelock_1.0.3             
#>   [3] tibble_3.3.1               
#>   [4] preprocessCore_1.72.0      
#>   [5] XML_3.99-0.22              
#>   [6] lifecycle_1.0.5            
#>   [7] httr2_1.2.2                
#>   [8] doParallel_1.0.17          
#>   [9] rprojroot_2.1.1            
#>  [10] processx_3.8.6             
#>  [11] lattice_0.22-7             
#>  [12] MASS_7.3-65                
#>  [13] MultiAssayExperiment_1.36.1
#>  [14] magrittr_2.0.4             
#>  [15] limma_3.66.0               
#>  [16] sass_0.4.10                
#>  [17] rmarkdown_2.30             
#>  [18] jquerylib_0.1.4            
#>  [19] yaml_2.3.12                
#>  [20] remotes_2.5.0              
#>  [21] otel_0.2.0                 
#>  [22] sessioninfo_1.2.3          
#>  [23] pkgbuild_1.4.8             
#>  [24] MsCoreUtils_1.22.1         
#>  [25] DBI_1.2.3                  
#>  [26] RColorBrewer_1.1-3         
#>  [27] abind_1.4-8                
#>  [28] pkgload_1.5.0              
#>  [29] GenomicRanges_1.62.1       
#>  [30] purrr_1.2.1                
#>  [31] AnnotationFilter_1.34.0    
#>  [32] RCurl_1.98-1.17            
#>  [33] rappdirs_0.3.4             
#>  [34] IRanges_2.44.0             
#>  [35] MSnbase_2.36.0             
#>  [36] commonmark_2.0.0           
#>  [37] ncdf4_1.24                 
#>  [38] codetools_0.2-20           
#>  [39] CompoundDb_1.14.2          
#>  [40] DelayedArray_0.36.0        
#>  [41] DT_0.34.0                  
#>  [42] xml2_1.5.2                 
#>  [43] tidyselect_1.2.1           
#>  [44] farver_2.1.2               
#>  [45] matrixStats_1.5.0          
#>  [46] BiocFileCache_3.0.0        
#>  [47] base64enc_0.1-6            
#>  [48] Seqinfo_1.0.0              
#>  [49] roxygen2_7.3.3             
#>  [50] diffobj_0.3.6              
#>  [51] jsonlite_2.0.0             
#>  [52] ellipsis_0.3.2             
#>  [53] iterators_1.0.14           
#>  [54] foreach_1.5.2              
#>  [55] progress_1.2.3             
#>  [56] tools_4.5.2                
#>  [57] snow_0.4-4                 
#>  [58] Rcpp_1.1.1                 
#>  [59] glue_1.8.0                 
#>  [60] gridExtra_2.3              
#>  [61] SparseArray_1.10.8         
#>  [62] BiocBaseUtils_1.12.0       
#>  [63] xfun_0.56                  
#>  [64] MatrixGenerics_1.22.0      
#>  [65] usethis_3.2.1              
#>  [66] withr_3.0.2                
#>  [67] BiocManager_1.30.27        
#>  [68] fastmap_1.2.0              
#>  [69] xopen_1.0.1                
#>  [70] callr_3.7.6                
#>  [71] digest_0.6.39              
#>  [72] rcmdcheck_1.4.0            
#>  [73] R6_2.6.1                   
#>  [74] rsvg_2.7.0                 
#>  [75] RSQLite_2.4.6              
#>  [76] tidyr_1.3.2                
#>  [77] data.table_1.18.2.1        
#>  [78] prettyunits_1.2.0          
#>  [79] PSMatch_1.14.0             
#>  [80] httr_1.4.8                 
#>  [81] htmlwidgets_1.6.4          
#>  [82] S4Arrays_1.10.1            
#>  [83] pkgconfig_2.0.3            
#>  [84] gtable_0.3.6               
#>  [85] blob_1.3.0                 
#>  [86] S7_0.2.1                   
#>  [87] impute_1.84.0              
#>  [88] MassSpecWavelet_1.76.0     
#>  [89] XVector_0.50.0             
#>  [90] brio_1.1.5                 
#>  [91] htmltools_0.5.9            
#>  [92] bookdown_0.46              
#>  [93] MALDIquant_1.22.3          
#>  [94] clue_0.3-67                
#>  [95] scales_1.4.0               
#>  [96] Biobase_2.70.0             
#>  [97] png_0.1-8                  
#>  [98] knitr_1.51                 
#>  [99] MetaboCoreUtils_1.19.2     
#> [100] rstudioapi_0.18.0          
#> [101] reshape2_1.4.5             
#> [102] rjson_0.2.23               
#> [103] curl_7.0.0                 
#> [104] cachem_1.1.0               
#> [105] stringr_1.6.0              
#> [106] BiocVersion_3.22.0         
#> [107] parallel_4.5.2             
#> [108] mzID_1.48.0                
#> [109] AnnotationDbi_1.72.0       
#> [110] vsn_3.78.1                 
#> [111] desc_1.4.3                 
#> [112] pillar_1.11.1              
#> [113] grid_4.5.2                 
#> [114] vctrs_0.7.1                
#> [115] MsFeatures_1.18.0          
#> [116] pcaMethods_2.2.0           
#> [117] dbplyr_2.5.2               
#> [118] cluster_2.1.8.1            
#> [119] waldo_0.6.2                
#> [120] evaluate_1.0.5             
#> [121] cli_3.6.5                  
#> [122] compiler_4.5.2             
#> [123] rlang_1.1.7                
#> [124] crayon_1.5.3               
#> [125] QFeatures_1.20.0           
#> [126] ChemmineR_3.62.0           
#> [127] ps_1.9.1                   
#> [128] affy_1.88.0                
#> [129] plyr_1.8.9                 
#> [130] fs_1.6.6                   
#> [131] stringi_1.8.7              
#> [132] Biostrings_2.78.0          
#> [133] lazyeval_0.2.2             
#> [134] devtools_2.4.6             
#> [135] Matrix_1.7-4               
#> [136] ExperimentHub_3.0.0        
#> [137] hms_1.1.4                  
#> [138] bit64_4.6.0-1              
#> [139] ggplot2_4.0.2              
#> [140] KEGGREST_1.50.0            
#> [141] statmod_1.5.1              
#> [142] SummarizedExperiment_1.40.0
#> [143] AnnotationHub_4.0.0        
#> [144] mzR_2.44.0                 
#> [145] igraph_2.2.2               
#> [146] memoise_2.0.1              
#> [147] affyio_1.80.0              
#> [148] bslib_0.10.0               
#> [149] bit_4.6.0
```
